Repository WildCodeSchool/orleans-0218-alphaseries, pull requests merged in 2018-05, with the labels that each got.

#136 Issue recherche partielle
  src/Model/SerieManager.php
Labels: issue

#137 Issue message erreur searchbar
  src/Controller/SerieController.php
  src/View/Serie/searchResult.html.twig
Labels: issue

#139 Fix selecteur
  src/Controller/EpisodeController.php
  src/Model/EpisodeManager.php
Labels: Reviewed by PO

#141 Fix
  public/assets/css/styles.css
  src/View/Home/index.html.twig
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/searchResult.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO, issue

#142 bouton plus responsive sur pageSerie
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO, issue

#140 Star rating
  public/assets/js/ratingStar.js
  src/View/Serie/inc_listEpisode.html.twig
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO

#145 Add new default picture
  .gitignore
  public/assets/upload/defaultPicture.jpg
  public/assets/upload/defaultPicture.png
  src/View/Home/index.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/listAdmin.html.twig
  src/View/Serie/pageSerie.html.twig
  src/View/Serie/searchResult.html.twig
Labels: Reviewed by PO

#146 alignement bouton edition episodes
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#143 Dev2
  composer.json
  public/assets/js/selecteurAjax.js
  src/Controller/EpisodeController.php
  src/Controller/SerieController.php
  src/Model/Episode.php
  src/Model/SerieManager.php
  src/View/Serie/inc_listEpisode.html.twig
  src/View/Serie/searchResult.html.twig
Labels: Reviewed by PO

#149 DevToMaster
  .gitignore
  app/routing.php
  composer.json
  public/assets/css/styles.css
  public/assets/js/ratingStar.js
  public/assets/js/selecteurAjax.js
  public/assets/upload/defaultPicture.jpg
  public/assets/upload/defaultPicture.png
  src/Controller/EpisodeController.php
  src/Controller/HomeController.php
  src/Controller/SerieController.php
  src/Controller/conditions_generales.html.twig
  src/Model/Episode.php
  src/Model/EpisodeManager.php
  src/Model/SerieManager.php
  src/View/Home/conditions_generales.html.twig
  src/View/Home/index.html.twig
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/inc_listEpisode.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/listAdmin.html.twig
  src/View/Serie/pageSerie.html.twig
  src/View/Serie/searchResult.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#150 Code Sniffer sur tout le projet
  public/assets/js/ratingStar.js
  public/assets/js/selecteurAjax.js
  src/Controller/AbstractController.php
  src/Controller/EpisodeController.php
  src/Controller/HomeController.php
  src/Controller/SeasonController.php
  src/Controller/SerieController.php
  src/Model/AbstractManager.php
  src/Model/Episode.php
  src/Model/EpisodeManager.php
  src/Model/HomeManager.php
  src/Model/Season.php
  src/Model/SeasonManager.php
  src/Model/Serie.php
  src/Model/SerieManager.php
Labels: Reviewed by PO

#151 Correction validator w3c
  src/View/Home/index.html.twig
  src/View/Serie/add.html.twig
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/listAdmin.html.twig
  src/View/Serie/pageSerie.html.twig
  src/View/Serie/searchResult.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#152 DevToMaster
  public/assets/js/ratingStar.js
  public/assets/js/selecteurAjax.js
  src/Controller/AbstractController.php
  src/Controller/EpisodeController.php
  src/Controller/HomeController.php
  src/Controller/SeasonController.php
  src/Controller/SerieController.php
  src/Model/AbstractManager.php
  src/Model/Episode.php
  src/Model/EpisodeManager.php
  src/Model/HomeManager.php
  src/Model/Season.php
  src/Model/SeasonManager.php
  src/Model/Serie.php
  src/Model/SerieManager.php
  src/View/Home/index.html.twig
  src/View/Serie/add.html.twig
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/listAdmin.html.twig
  src/View/Serie/pageSerie.html.twig
  src/View/Serie/searchResult.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#153 Duplicate file
  src/Controller/conditions_generales.html.twig
Labels: Reviewed by PO

#154 Dev
  src/Controller/conditions_generales.html.twig
Labels: Reviewed by PO

#155 fix note moyenne numerique
  public/assets/css/styles.css
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO

#156 Fix
  public/assets/css/styles.css
Labels: Conflicts

#158 Add cursor: pointer on stars notation
  public/assets/css/styles.css
Labels: Reviewed by PO

#157 DevToMaster
  public/assets/css/styles.css
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO
