Repository WildCodeSchool/orleans-0218-alphaseries, pull requests merged in 2018-04, with the labels that each got.

#9 Navbar
  .gitignore
  public/assets/css/styles.css
  src/View/layout.html.twig
Labels: Reviewed by PO

#11 Footer
  public/assets/css/styles.css
  src/View/layout.html.twig
Labels: Reviewed by PO

#10 Us3 liste serie
  .gitignore
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/bg.jpg
  public/assets/images/favicon.png
  src/Controller/SerieController.php
  src/Model/Serie.php
  src/Model/SerieManager.php
  src/View/Serie/list.html.twig
Labels: Conflicts, Reviewed by PO

#15 Index
  app/routing.php
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/Controller/SerieController.php
  src/Model/HomeManager.php
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Correction Done, Reviewed by PO

#17 reglage du footer
  public/assets/css/styles.css
  src/View/layout.html.twig
Labels: Reviewed by PO

#21 Police
  app/routing.php
  public/assets/css/fonts/texgyreadventor-regular-webfont.woff
  public/assets/css/styles.css
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#25 logo
  app/db.php.dist
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/ecran Alpha.png
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#28 arrangement des lien
  src/View/layout.html.twig
Labels: Reviewed by PO

#29 Searbar liste
  app/routing.php
  public/assets/css/styles.css
  src/Controller/SerieController.php
  src/Model/SerieManager.php
  src/View/Home/index.html.twig
  src/View/Serie/searchResult.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#30 Seriedescription
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/penny.png
  src/Controller/SerieController.php
  src/Model/AbstractManager.php
  src/View/Serie/list.html.twig
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO

#31 Taillepolice
  public/assets/css/styles.css
  public/assets/images/ecran_alpha.png
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#27 creation de la pagination
  app/routing.php
  src/Controller/SerieController.php
  src/Model/AbstractManager.php
  src/Model/SerieManager.php
  src/View/Serie/list.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#34 Fix
  public/assets/css/styles.css
  public/assets/upload/defaultPicture.jpg
  src/View/Home/index.html.twig
  src/View/Serie/add.html.twig
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/pageSerie.html.twig
  src/View/Serie/searchResult.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#35 Dev
  public/assets/css/styles.css
  public/assets/upload/defaultPicture.jpg
  src/View/Home/index.html.twig
  src/View/Serie/add.html.twig
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/pageSerie.html.twig
  src/View/Serie/searchResult.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#37 reglage du responsive
  src/View/Serie/list.html.twig
Labels: Reviewed by PO

#51 Us17 searchbar on searchresult page
  src/View/Serie/searchResult.html.twig
Labels: Reviewed by PO

#53 Us15 searchbar on serielist
  src/View/Serie/list.html.twig
Labels: Reviewed by PO

#38 List administrable
  app/routing.php
  public/assets/css/styles.css
  src/Controller/SerieController.php
  src/View/Serie/listAdmin.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#55 Update fonction
  .gitignore
  app/routing.php
  public/assets/upload/defaultPicture.png
  src/Controller/SerieController.php
  src/Model/AbstractManager.php
  src/Model/SerieManager.php
  src/View/Serie/add.html.twig
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#57 Logo
  public/assets/css/styles.css
  public/assets/images/ecran_alpha.png
  public/assets/images/ecran_alpha2.png
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#58 Delete serie
  app/routing.php
  src/Controller/SerieController.php
  src/Model/AbstractManager.php
  src/Model/SerieManager.php
  src/View/Serie/listAdmin.html.twig
Labels: Reviewed by PO

#59 Apropos
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/Model/HomeManager.php
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#60 Ajout saison
  app/routing.php
  src/Controller/SeasonController.php
  src/Controller/SerieController.php
  src/Model/Season.php
  src/Model/SeasonManager.php
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#66 Fix saison 0
  src/Controller/SeasonController.php
Labels: Reviewed by PO

#65 Proposition choix supprimer ou non image
  src/Controller/SerieController.php
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#67 rectification du css
  public/assets/css/styles.css
  src/View/layout.html.twig
Labels: Reviewed by PO

#68 alignement des labels
  src/View/Serie/add.html.twig
Labels: Reviewed by PO

#69 Corrections done
  src/Controller/SerieController.php
  src/Model/Serie.php
  src/Model/SerieManager.php
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#73 Update adminSerie.html.twig
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#70 Centering of elements in admin
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#72 Dev
  .gitignore
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/ecran_alpha.png
  public/assets/images/ecran_alpha2.png
  public/assets/upload/defaultPicture.png
  src/Controller/HomeController.php
  src/Controller/SeasonController.php
  src/Controller/SerieController.php
  src/Model/AbstractManager.php
  src/Model/HomeManager.php
  src/Model/Season.php
  src/Model/SeasonManager.php
  src/Model/Serie.php
  src/Model/SerieManager.php
  src/View/Home/index.html.twig
  src/View/Serie/add.html.twig
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/listAdmin.html.twig
  src/View/Serie/searchResult.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#74 Fix upload
  src/Controller/SerieController.php
Labels: Reviewed by PO

#78 affichage de la page actuelle et de la page max
  src/View/Serie/list.html.twig
Labels: Reviewed by PO

#96 selecteur de saison sur page dédier
  src/Controller/SerieController.php
  src/Model/SeasonManager.php
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO

#76 Add episode
  app/routing.php
  public/assets/css/styles.css
  src/Controller/EpisodeController.php
  src/Controller/SeasonController.php
  src/Controller/SerieController.php
  src/Model/AbstractManager.php
  src/Model/Episode.php
  src/Model/EpisodeManager.php
  src/Model/Season.php
  src/Model/SeasonManager.php
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/test.html.twig
Labels: Reviewed by PO

#97 Episode serie
  src/Controller/SerieController.php
  src/Model/EpisodeManager.php
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#98 pagination admin plus lien
  app/routing.php
  src/Controller/SerieController.php
  src/View/Serie/listAdmin.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#101 Dev
  app/routing.php
  public/assets/css/styles.css
  src/Controller/EpisodeController.php
  src/Controller/SeasonController.php
  src/Controller/SerieController.php
  src/Model/AbstractManager.php
  src/Model/Episode.php
  src/Model/EpisodeManager.php
  src/Model/Season.php
  src/Model/SeasonManager.php
  src/Model/SerieManager.php
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/listAdmin.html.twig
  src/View/Serie/pageSerie.html.twig
  src/View/Serie/test.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#103 Changement redirection after update série
  src/Controller/SerieController.php
Labels: Reviewed by PO

#102 style card
  public/assets/css/styles.css
  src/View/Home/index.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/listAdmin.html.twig
  src/View/Serie/searchResult.html.twig
Labels: Reviewed by PO

#104 Mise en forme des Exceptions
  src/Controller/EpisodeController.php
  src/Controller/SeasonController.php
  src/Controller/SerieController.php
  src/View/Serie/add.html.twig
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#108 size title
  public/assets/css/styles.css
Labels: Reviewed by PO

#109 Suppression d'une vue
  src/View/Serie/test.html.twig
Labels: Reviewed by PO

#110 Ajout propriete global note dans Serie.php
  src/Model/Serie.php
Labels: Reviewed by PO

#111 change style button
  public/assets/css/styles.css
Labels: Reviewed by PO

#112 change style card
  public/assets/css/styles.css
Labels: Reviewed by PO

#105 Display episodes sort by season and episode's number
  src/Controller/SerieController.php
  src/Model/EpisodeManager.php
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#113 Modification vue saison sélecteur
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO

#115 Vue number s0 e0
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/inc_listEpisode.html.twig
Labels: Reviewed by PO

#114 Add switch checkbox
  public/assets/css/styles.css
  src/View/Serie/inc_listEpisode.html.twig
Labels: Reviewed by PO

#119 Fix stars color
  public/assets/css/styles.css
Labels: Reviewed by PO

#120 Changement Background episodes en ajax
  public/assets/css/styles.css
  src/View/Serie/inc_listEpisode.html.twig
Labels: Reviewed by PO

#121 US14 checkbox all vus
  public/assets/js/selecteurAjax.js
  src/View/Serie/inc_listEpisode.html.twig
Labels: Reviewed by PO

#122 Fix champ creationDate
  src/Controller/SerieController.php
  src/View/Serie/add.html.twig
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#123 fix
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO

#124 Dev
  app/routing.php
  public/assets/css/styles.css
  public/assets/js/selecteurAjax.js
  src/Controller/EpisodeController.php
  src/Controller/SeasonController.php
  src/Controller/SerieController.php
  src/Model/EpisodeManager.php
  src/Model/SeasonManager.php
  src/Model/Serie.php
  src/View/Home/index.html.twig
  src/View/Serie/add.html.twig
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/inc_listEpisode.html.twig
  src/View/Serie/list.html.twig
  src/View/Serie/listAdmin.html.twig
  src/View/Serie/pageSerie.html.twig
  src/View/Serie/searchResult.html.twig
  src/View/Serie/test.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#118 Us5 edition episodes
  app/routing.php
  src/Controller/EpisodeController.php
  src/Model/EpisodeManager.php
  src/View/Serie/adminSerie.html.twig
Labels: Reviewed by PO

#125 Fix twig format
  src/View/Serie/inc_listEpisode.html.twig
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO

#126 Dev
  app/routing.php
  src/Controller/EpisodeController.php
  src/Model/EpisodeManager.php
  src/View/Serie/adminSerie.html.twig
  src/View/Serie/inc_listEpisode.html.twig
  src/View/Serie/pageSerie.html.twig
Labels: Reviewed by PO

#127 Formatage taille image
  public/assets/css/styles.css
Labels: Reviewed by PO
